---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: hybrid
    name: 'cluster01'
    cluster.open-cluster-management.io/clusterset: 'default'
    clusterType: 'sno'
  name: 'cluster01'
spec:
  hubAcceptsClient: true
