---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#commonLabels:
#  demo: open5gs

namespace: cluster01

bases:
- ../cluster-install

resources:
- 03-managed-cluster.yaml
- 04-kluster-addon-config.yaml
