---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#commonLabels:
#  demo: open5gs

namespace: cluster01

bases:
- ../base

resources:
- 01-bare-metal-host.yaml
- 02-nmstate-config.yaml
- 02-infra-env.yaml
- 02-pull-secret.yaml
