---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#commonLabels:
#  demo: open5gs

namespace: cluster01

bases:
- ../host-inventory

resources:
- 00-extra-manifests-cm.yaml
- 02-cluster-deployment.yaml
- 03-agent-cluster-install.yaml
